### ISSUE TITLE
Bug na edição do perfil

### ISSUE THREAD

**Issue by All3yp** [jhennyferOliveira/DiarioDeAprendizado#39]
Está quebrando na edição do usuário e como consequência, esse usuário é deletado, pois não consigo mais logar no mesmo. 

![photo_2020-04-02_10-26-37](https://user-images.githubusercontent.com/29764688/78254615-93cc1f80-74cc-11ea-9c94-39366934dcf2.jpg)

**Comment by viniciusmesquitac** [comment]
Massa! caramba, eu ainda não sei se resolvi o erro, mas, em alguns momentos o usuario tava vindo como nulo, se fiz umas alterações e gostaria que testasse dnv se der.

#### Error [illegal hardware instruction / Illegal Instruction: 4]


arquivo: UserOptions.swift

adicionado em _editInformation()_:
```swift
    guard currentUser != nil else {
            print("what")
            return
        }
```
