### ISSUE TITLE
Resposta pro usuário

### ISSUE THREAD

**Issue by helainepontes** [jhennyferOliveira/DiarioDeAprendizado#43]
Dupla: 
Helaine e Hiago

Sugestão:
Implementar respostas pro usuário, por exemplo, ao alterar um título de alguma anotação, mostrar que foi alterado com sucesso e assim para todas as funcionalidades.

P.s: O código ficou bem organizado, parabéns

**Comment by viniciusmesquitac** [comment]
Muito obrigado pelo alerta galera! :D vamos ver isso com certeza!
